CREATE DATABASE CoffeeShop
USE CoffeeShop

CREATE TABLE Products
(
ID INT PRIMARY KEY IDENTITY,
ProductName NVARCHAR(255) UNIQUE NOT NULL,
IsServedHot BIT,
ProductPrice DECIMAL(18,2) NOT NULL,
)
CREATE TABLE Ingridients
(
ID INT PRIMARY KEY IDENTITY,
IngridientName NVARCHAR(255) NOT NULL,
ProductID INT FOREIGN KEY REFERENCES Products(ID)
)
CREATE TABLE Customers
(
ID INT PRIMARY KEY IDENTITY,
CustomerName NVARCHAR(255) NOT NULL
)
CREATE TABLE Orders
(
ID INT PRIMARY KEY IDENTITY,
CustomerID INT FOREIGN KEY REFERENCES Customers(ID),
ProductID INT FOREIGN KEY REFERENCES Products(ID)
)